# Generated by Django 5.1.2 on 2024-11-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
