# Generated by Django 5.1.2 on 2024-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carelog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
