# Generated by Django 5.1.2 on 2024-11-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_carelog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Bi-weekly', 'Bi-weekly')], default='Weekly', max_length=50)),
                ('last_watered', models.DateField(blank=True, null=True)),
                ('next_watering', models.DateField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_schedules', to='app.plant')),
            ],
        ),
    ]
