# Generated by Django 5.1.2 on 2024-11-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_wateringschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
