# Generated by Django 5.1.2 on 2024-11-27 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_plant_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='carelog',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plant'),
        ),
        migrations.AlterField(
            model_name='healthstatus',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plant'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plant'),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plant'),
        ),
    ]
